# Generated by Django 4.1.2 on 2023-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('payment', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium')], max_length=50)),
            ],
        ),
    ]
