# Generated by Django 4.1.2 on 2023-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzerio_API', '0003_subscription_requests_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
