# Generated by Django 4.1.2 on 2023-02-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0002_food_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='requests',
        ),
    ]
